apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: realty
  name: database-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /home/alexwfs/realty